server:
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.sobasizzle.com
    annotations:
      kubernetes.io/ingress.class: traefik
      # Traefik specific annotations can be added here if needed
    paths:
      - /
  config:
    params:
      server.insecure: "true"
